/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118380-gca3550948c-20250129"
#endif /* AVUTIL_FFVERSION_H */
